# https://taskfile.dev

version: '3'

vars:
  image: git.5wp.de/ceddy/killspiel
  build: ../build

tasks:
  frontend:
    dir: frontend
    env:
      VITE_BACKEND_URL:
    cmds:
      - pnpm run build
    sources:
      - frontend/src/**/*.{svelte,js.ts}
      - frontend/static
    generates:
      - frontend/build
  cp:
    cmds:
      - pwsh -c rm -r ".\Backend\frontend_build\*"
      - pwsh -c "cp -r frontend/build/* backend/frontend_build/"
    deps:
      - frontend
    sources:
      - frontend/build/*
    generates:
      - backend/frontend_build/*

  backend:
    cmds:
      - go build main.go
    dir: backend
    sources:
      - backend/main.go
      - backend/**/*.go
      - backend/go.mod
      - backend/frontend_build
    generates:
      - backend/main.exe


  build:
    cmds:
      - task: cp
      - task: backend

  docker:
    cmds:
      - docker buildx build -f Dockerfile -t {{.image}} .

  windows-icon:
    dir: backend/icon
    cmd: windres -o ../main-res.syso main.rc

  push:
    cmd: docker push {{.image}}

  publish:
    deps:
      - cp
    cmd: task publish:intern

  publish:intern:
    deps:
      - publish:win
      - publish:linux:arm
      - publish:linux:arm:64
      - publish:linux:64

  publish:win:
    internal: true
    env:
      GOOS: windows
      GOARCH: amd64
    dir: backend
    # -ldflags "-H windowsgui" for hidden shell
    # TODO before adding this, add logging to file
    # drawback: even in shell, no log anymore
    cmd: go build -o {{.build}}/Killspiel_win_x64.exe . # if main.go instead of ., the icon won't be used

  publish:linux:arm:
    internal: true
    env:
      GOOS: linux
      GOARCH: arm
    dir: backend
    cmd: go build -o {{.build}}/Killspiel_linux_arm main.go

  publish:linux:arm:64:
    internal: true
    env:
      GOOS: linux
      GOARCH: arm64
    dir: backend
    cmd: go build -o {{.build}}/Killspiel_linux_arm64 main.go

  publish:linux:64:
    internal: true
    env:
      GOOS: linux
      GOARCH: amd64
    dir: backend
    cmd: go build -o {{.build}}/Killspiel_linux_x64 main.go