# https://taskfile.dev

version: '3'

vars:
  image: git.5wp.de/ceddy/killspiel

tasks:
  frontend:
    dir: frontend
    env:
      VITE_BACKEND_URL:
    cmds:
      - pnpm run build
    sources:
      - frontend/src/**/*.{svelte,js.ts}
      - frontend/static
    generates:
      - frontend/build
  cp:
    cmds:
      - pwsh -c rm -r ".\Backend\frontend_build\*"
      - pwsh -c "cp -r frontend/build/* backend/frontend_build/"
    deps:
      - frontend
    sources:
      - frontend/build/*
    generates:
      - backend/frontend_build/*
    internal: true


  backend:

    cmds:
      - go build -ldflags "-X main.DisableStartupMessage=true" main.go
    dir: backend
    sources:
      - backend/main.go
      - backend/**/*.go
      - backend/go.mod
      - backend/frontend_build
    generates:
      - backend/main.exe


  build:
    cmds:
      - task: cp
      - task: backend

  docker:
    cmds:
      - docker buildx build -f Dockerfile -t {{.image}} .

  push:
    cmd: docker push {{.image}}