# https://taskfile.dev

version: '3'

tasks:
  frontend:
    dir: frontend
    env:
      VITE_BACKEND_URL:
    cmds:
      - pnpm run build
    sources:
      - frontend/src/**/*.{svelte,js.ts}
      - frontend/static
    generates:
      - frontend/build
  cp:
    cmds:
      - pwsh -c rm -r ".\Backend\frontend_build\*"
      - pwsh -c "cp -r frontend/build/* backend/frontend_build/"
    deps:
      - frontend
    sources:
      - frontend/build/*
    generates:
      - backend/frontend_build/*
    internal: true

  fixFrontend:
    cmds:
      - py fixFrontend.py
    deps:
      - cp

  backend:

    cmds:
      - go build main.go
    dir: backend
    sources:
      - backend/main.go
      - backend/**/*.go
      - backend/go.mod
      - backend/frontend_build
    generates:
      - main.exe


  build:
    cmds:
      - task: fixFrontend
      - task: backend